apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-proxy
spec:
  replicas: {{ .Values.nginxProxy.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: nginx:latest
          ports:
            - containerPort: 80

